# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  #config.vm.box = "bento/ubuntu-16.04"
  config.vm.box = "generic/ubuntu1804"

  config.vm.define "manager1", primary: true do |manager1|
    manager1.vm.network "private_network", ip: "192.168.50.100"
    manager1.vm.hostname = "manager1"

    manager1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	  vb.cpus = 1
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.network "private_network", ip: "192.168.50.101"
    worker1.vm.hostname = "worker1"

    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	  vb.cpus = 1
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.network "private_network", ip: "192.168.50.102"
    worker2.vm.hostname = "worker2"

    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	  vb.cpus = 1
    end
  end
end
