# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  #config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.define "manager1", primary: true do |manager|
    manager.vm.network "private_network", ip: "172.17.4.100"
    manager.vm.hostname = "manager1"

    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	    vb.cpus = 1
    end

    #manager.vm.provision :shell, path: "manager.sh"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.network "private_network", ip: "172.17.4.101"
    worker1.vm.hostname = "worker1" 

    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	    vb.cpus = 1
    end

    #worker1.vm.provision :shell, path: "worker.sh"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.network "private_network", ip: "172.17.4.102"
    worker2.vm.hostname = "worker2"

    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
	    vb.cpus = 1
    end

    #worker2.vm.provision :shell, path: "worker.sh"
  end
end
